# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: dotjs
title_html: d<span></span>tjs
email: team@dotjs.app
description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut maxime voluptatum, veritatis quod aperiam quis ipsum. Excepturi aspernatur doloribus fuga tenetur explicabo harum, maiores deleniti facilis placeat, asperiores libero repellat!'
baseurl: /
theme_color: aa5561
navigation:
    -
        label: home
        link: /
    -
        label: blog
        link: https://medium.com/@dotjs
        target: _blank
    -
        label: contact
        link: mailto:hello@dotjs.app
url: https://dotjs.app
twitter_username: HelloDotJS
assets:
    sources:
        - assets/fonts
markdown: kramdown
theme: minima
plugins:
    - jekyll-feed


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
